#! /bin/sh

betterlockscreen -w &
blurwal -s 20 -b 5 -m 1 &
sxhkd &
~/.config/polybar/launch.sh &
killall -q compton; compton -b &
udiskie &
~/.scripts/floating &
libinput-gestures-setup start &

bspc monitor -d firefox discord term code music mail pass git 9 10

bspc config border_width         0
bspc config window_gap          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#565c64"
bspc config focused_border_color "#abb2bf"
bspc config urgent_border_color "#e06c75"
bspc config presel_border_color "#61afef"

bspc rule -a feh state=floating center=true
bspc rule -a mpv state=floating center=true
bspc rule -a Enpass desktop=^7
bspc rule -a discord-canary desktop=^2
bspc rule -a jetbrains-clion desktop=^4
bspc rule -a code-oss desktop=^4
bspc rule -a spotify desktop=^5

